theme: jekyll-theme-minimal
title: Pagina principal en Git de RevDev
description: Somos la parte de ingenieria de ideas, generamos esquemas, desarrollamos proyectos, agradecemos por cada paso que damos, hasta llegar a la salida a la luz del proyecto, bienvenidos 
